### ISSUE TITLE
Add TOC for Week1

### ISSUE THREAD

**Issue by amanchhaparia** [SRA-VJTI/computer-vision-study-group#1]
Add a Table of Content for the week 1.
Reference: [Embedded Study Group](https://github.com/SRA-VJTI/embedded-systems-study-group/blob/master/week1/week1.md)
@vrnimje

**Comment by vrnimje** [comment]
Added the Table of contents for week 1 notes
https://github.com/SRA-VJTI/computer-vision-study-group/pull/2
@amanchhaparia
